title: blueGorae's website
description: > # this means to ignore newlines until "baseurl:"
  blueGorae's website
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bluegorae.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Seongtae Kim # add your name
author-img: profile.jpg # add your photo
about-author: I am an AI researcher, particularly in computer vision and graphics. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: blueGorae # add your Github handle
social-linkedin: seongtaekim-05ba20162 # add your Linkedin handle
social-email: seongtae@neosapience.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: G-F47GQTKXGZ # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
